on:
  workflow_run:
    workflows: [pre-commit]
    types: [completed]
jobs:
  mirror_repo:
    environment: GITLAB
    runs-on: self-hosted
    steps:
      - name: step1
        run: |
          #!/bin/bash
          curl --request POST --header "PRIVATE-TOKEN:${{ secrets.TOKEN }}" "${{ secrets.MIRROR_URL }}"
